# Generated by Django 6.0.4 on 2026-07-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('historico', models.TextField(verbose_name='Histórico')),
                ('estadio_url', models.URLField(blank=True, verbose_name='URL do Estádio')),
            ],
            options={
                'verbose_name': 'Página Inicial',
                'verbose_name_plural': 'Páginas Iniciais',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.URLField(verbose_name='Foto')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('posicao', models.CharField(max_length=80, verbose_name='Posição')),
                ('nascimento', models.CharField(max_length=120, verbose_name='Naturalidade')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_nome', models.CharField(max_length=160, verbose_name='Nome do Site')),
                ('autor', models.CharField(max_length=120, verbose_name='Autor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
            },
        ),
    ]
